### ISSUE TITLE
Свой же сайт?

### ISSUE THREAD

**Issue by Sergdan1992** [opengs/uashieldtargets#6]
https://help-ukraine-win.com/ - зачем ddos-или свой же сайт?

**Comment by naharar** [comment]
> https://help-ukraine-win.com/ - зачем ddos-или свой же сайт?

https://github.com/opengs/uashieldtargets/commit/f315f20bc546297b29c8d488d0c81af84b2519f4 Человеческий фактор или 5 колонна?

**Comment by SurpSG** [comment]
А можна роз'яснень що сталося? Я вирубив всі інстанси uashield, бо немає впевненості, що він не скомпроментований

**Comment by Sergdan1992** [comment]
> А можна роз'яснень що сталося? Я вирубив всі інстанси uashield, бо немає впевненості, що він не скомпроментований

В якийсь момент побачив що в списку єдиний сайт і це той де я знайшов ваше ПО. Я потім знайшов issue-с, що це було задля тесту!
